#!/bin/bash

# Below can be found a list of what each error code means

err0="Code 0: Not an error. This being set means last time abs was ran it exited with no problems"
err1="Code 1: Could not find user provided archiso profile. This can be caused either by an incorrectly spelled profile or abs was not called in your iso's build directory."
err2="Code 2: Could not find xerolinux profile. Almost certainly caused by abs being called with the xero option in the wrong directory."
err3="Code 3: Option passed in through terminal is not a valid option."
err4="Code 4: Not an error. If this code was set it means abs help was the most recent abs option used."
err5="Code 5: Ctrl C aka SigTerm2 was detected. Forcing abs exit"
err6="Code 6: Last time abs was ran was as sudo/root and was caught by sudoCheck function forcing exit."
err7="Code 7: Last time abs was ran it could not connec to the internet and was caught by checkInternetConnection forcing exit."
err8="Code 8: Last time abs was ran the latest archiso check failed and was caught by isArchisoUpToDate forcing exit."
