#!/bin/bash
#set -e

source /etc/abs/misc/.bashFormatting
source /etc/abs/.options

trap_ctrlc() {
	echo
    echo "Ctrl-C detected. Ending current abs session."
    exit
}

trap "trap_ctrlc" 2


cloneGit() {
	read -p "Would you like to clone the latest ${1} git to your home directory? (${fgGreen}Y${txReset}/${fgRed}N${txReset}): " YN
	finished="0"
	profileSelection=$1
	while [ finished != 1 ]; do
	case $YN in
		y | Y | yes | Yes | YES )
			echo "Oki, cloning repo now."
			if [[ $profileSelection == "xero" ]]; then
				git clone https://github.com/xerolinux/xero_iso.git ~/xero_iso
			elif [[ $profileSelection == "xerog" ]]; then
				git clone https://github.com/XeroLinuxDev/xero_g_iso.git ~/xero_g_iso
			else
				echo "This never happens. Congrats"
			fi
			finished='1'
			echo "Done."
			;;
		n | N | no | No | NO )
			echo "Oki. abs will not clone. Please run abs in the directory containing the xero profile"
			finished='1'
			;;
		* )
			echo "abs does not understand your response. Please try again. ${fgGreen}Y${txReset} or ${fgRed}N${txReset}."
			read -p "Would you like to clone the latest ${1} git to your home directory?: " YN
			;;
	esac
	done
}

absC() {
	echo "Oki, let's get ready to build a custom iso using a user provided profile."
	read -p "What is the name of the archiso profile abs will be building your iso with? : " archisoProfile
	echo
	echo "Scanning for provided archiso profile."
	if [[ ! -d $archisoProfile ]]; then
		echo "Couldn't find the archiso profile you provided in the current directory."
		echo "Please change to the proper directory and call abs once more."
	else
		echo "abs found your archiso profile. abs will now begin your iso's build process."
		custom
	fi
}

absX() {
	echo "Oki, let's get ready to build a Xero iso from the provided xero profile."
	echo
	echo "Scanning for Xero profile."
	if [[ ! -d Xero ]]; then
		echo "Couldn't find the xerolinux profile in the current directory."
		cloneGit xero
	else
		echo "abs found the xerolinux profile. abs will now begin the xero build process." && sleep 1.7
		xero
	fi
}

absXg() {
	echo "Oki, let's get ready to build a XeroG iso from the provided XeroG profile."
	echo
	echo "Scanning for XeroG profile."
	if [[ ! -d XeroG ]]; then
		echo "Couldn't find the XeroG profile in the current directory."
		cloneGit xerog
	else
		echo "abs found the xerolinux profile. abs will now begin the xero build process." && sleep 1.7
		xerog
	fi
}

if [[ $1 == "help" || $1 == "-help" || $1 == "-h" || $1 == "-H" ]]; then
	helpOpt
elif [[ $1 == "custom" || $1 == "Custom" || $1 == "CUSTOM" || $1 == "-c" || $1 == "-C" ]]; then
	absC
elif [[ $1 == "xero" || $1 == "Xero" || $1 == "XERO" || $1 == "xerolinux" || $1 == "XeroLinux" || $1 == "Xerolinux" || $1 == "xeroLinux" || $1 == "-x" || $1 == "-X" ]]; then
	absX
elif  [[ $1 == "xerog" || $1 == "Xerog" || $1 == "XeroG" ]]; then
	absXg
elif [[ -n $1 ]]; then
	echo "Sorry, abs does not recognize this option. Run ${fgCyan}abs -help${txReset} for a list of accepted options and their brief descriptions."
else
	read -p "Are you looking to build a ${fgCyan}${txUnderline}custom${txReset} iso or ${fgCyan}${txUnderline}xero${txReset} iso or do you need ${fgRed}help${txReset}? " answer
	finished='0'
	while [ finished != 1 ]; do
	case $answer in
		custom | Custom | CUSTOM | -C | -c )
			finished='1'
			absC
			;;
		xero | XERO | xerolinux | XeroLinux | Xerolinux | xeroLinux | XEROLINUX | -x | -X )
			finished='1'
			absX
			;;
		XeroG | xerog | Xerog )
			finished='1'
			absXg
			;;
		help | -h | -H | HELP | help )
			helpOpt
			;;
		* )
			echo "Not a valid abs option. Enter ${fgCyan}${txUnderline}custom${txReset} or ${fgCyan}${txUnderline}xero${txReset}"
			echo "Additionally you can run ${fgCyan}abs help${txReset} for abs options and descriptions."
			read -p "Are you looking to build a ${fgCyan}${txUnderline}custom${txReset} iso or a ${fgCyan}${txUnderline}xero${txReset} iso? " answer
			;;
	esac
	done
fi

# Functionality for the future potentially
# Error catching
#	echo "${txBold}last-error${txReset}"
#	echo "Adding this option to abs will print last exit/err code abs set when last ran."
#	echo $fgMagenta&&xUnicode 2730 49&&echo $txReset
