#!/bin/bash
# https://keyaedisa.github.io/

export BT="absd"

source /etc/$BT/misc/.bashFormatting
source /etc/$BT/misc/.functions
source /etc/$BT/.options

if [[ $1 == "-c" || $1 == "custom" ]]; then
	custom
elif [[ $1 == "-h" || $1 == "--help" ]]; then
	helpOpt $1
elif [[ $1 == "-L" ]]; then
	listOpt
elif  [[ $1 == "-v" || $1 == "vanilla" || $1 == "releng" ]]; then
	vanilla
elif  [[ $1 == "-vb" || $1 == "vanillaBaseline" || $1 == "baseline" ]]; then
	vanillaBaseline
elif [[ $1 == "-x" || $1 == "xero" ]]; then
	xero
elif  [[ $1 == "-xg" || $1 == "xerog" ]]; then
	xerog
elif [[ -n $1 ]]; then # If stdin is a not empty string not matching any  of the previous conditions then:
	echo "Sorry, ${BT} does not recognize this option. Run ${fgCyan}${BT} -h${txReset} or ${fgCyan}${BT} --help (for more detailed version)${txReset} to display help message."
else
	listOpt
	read -p "What option would you like to select? " answer
	finished='0'
	while [ finished != 1 ]; do
	case $answer in
		-c | custom )
			finished='1'
			custom
			;;
		-h | --help )
			helpOpt $answer
			;;
		-L )
			listOpt
			;;
		-v | vanilla | releng )
			finished='1'
			vanilla
			;;
		-vb | vanillaBaseline | baseline )
			finished='1'
			vanillaBaseline
			;;
		-x | xero )
			finished='1'
			xero
			;;
		-xg | xerog )
			finished='1'
			xerog
			;;
		* )
			echo "Not a valid ${BT} option. Enter ${fgCyan}${txUnderline}custom${txReset} or ${fgCyan}${txUnderline}xero${txReset}"
			echo "Additionally you can run ${fgCyan}${BT} help${txReset} for ${BT} options and descriptions."
			read -p "Are you looking to build a ${fgCyan}${txUnderline}custom${txReset} iso or a ${fgCyan}${txUnderline}xero${txReset} iso? " answer
			;;
	esac
	done
fi

# Functionality for the future potentially
# Error catching
#	echo "${txBold}last-error${txReset}"
#	echo "Adding this option to ${BT} will print last exit/err code ${BT} set when last ran."
#	echo $fgMagenta&&xUnicode 2730 49&&echo $txReset
