post_upgrade() {
	echo
	echo "New abs update succesfully installed!"
	echo "If you are a distro maintainer and are interested in integrating your distro into abs reach out!
	echo "https://keyaedisa.github.io, https://github.com/keyaedisa "
}

post_install() {
	echo
	echo "Thanks for installing abs! I'm sure you will love it. If you need assistance try abs -h/--help!"
	echo "If you are a distro maintainer and are interested in integrating your distro into abs reach out!
	echo "https://keyaedisa.github.io, https://github.com/keyaedisa "
}

post_remove() {
 echo
 echo "Sad to see you go! Please reach out to Keyaedisa if theres anyway they can bring you back!"
 echo "https://keyaedisa.github.io, https://github.com/keyaedisa "
}
