#!/bin/bash

# Copy contents of absd dir to abs dir -> rename absd file in abs dir to abs -> change $BT from ="absd" to ="abs"
# -> rename all absd refs in PKGBUILD to abs -> change source in makepkg back to the production abs one

# log current production and dev abs/d versions
currentDevPkgVer=$(sed -n 's/\(^pkgver=\)//p' PKGBUILD )
currentDevPkgRel=$(sed -n 's/\(^pkgrel=\)//p' PKGBUILD )
currentProdPkgVer=$(sed -n 's/\(^pkgver=\)//p' ../abs/PKGBUILD )
currentProdPkgRel=$(sed -n 's/\(^pkgrel=\)//p' ../abs/PKGBUILD )

# cp over necesary files with updates to production abs repo
cp -r options/ ../abs/
cp -r absd ../abs/
cp -r PKGBUILD ../abs/

# delete unneccessary files and rename absd to abs
rm ../abs/abs
mv ../abs/absd ../abs/abs

# change all absd refs to abs in all files
sed 's/absd/abs/g' ../abs/abs
sed 's/absd/abs/g' ../abs/options/.options
sed 's/absd/abs/g' ../abs/options/custom
sed 's/absd/abs/g' ../abs/options/help
sed 's/absd/abs/g' ../abs/options/xero
sed 's/absd/abs/g' ../abs/options/xerog
sed 's/absd/abs/g' ../abs/PKGBUILD

# set url in PKGBUILD back to production abs repo
sed 's/ssh:\/\/git@github.com\/keyaedisa\/absd.git/https:\/\/github.com\/keyaedisa\/abs.git/' ../abs/PKGBUILD
