#!/bin/bash
# https://keyaedisa.github.io, https://github.com/keyaedisa

set -e

devRepo="valenDev_repo"
prodRepo="valen_repo"

# define package variables using this pkgs PKGBUILD, most if not all will be rewritten by end of script
cPkgVer=$(sed -n 's/\(^pkgver=\)//p' PKGBUILD	)
cPkgRel=$(sed -n 's/\(^pkgrel=\)//p' PKGBUILD	)
cPkgName=$(sed -n 's/\(^pkgname=\)//p' PKGBUILD | sed 's/\([^"]*\)./\1/gi')
cPkgArch=$(sed -n 's/\(^arch=\)//p' PKGBUILD | sed 's/\([^\(\)]*\)./\1/gi' | sed "s/\([^']*\)./\1/gi")
package="${cPkgName}-${cPkgVer}-${cPkgRel}-${cPkgArch}.pkg.tar.zst"


echo "Preparing to build ${cPkgName} for ${cPkgArch}!"
echo

fin=0
while [ $fin = 0 ]; do
read -p "When done building push to dev or production repo? (d/p) : " dp
case $dp  in
	d | dev | development )
		echo "Oki. Will push to development Valen repo when done!"
		destRepo=$devRepo
		fin='1'
		;;
	p | prod | production )
		echo "Oki. Will push to production Valen repo when done!"
		destRepo=$prodRepo
		fin='1'
		;;
	* )
		echo "Not a valid option. Please enter dev or prod."
		;;
esac
done

echo "First we check if anything in PKGBUILD needs updating."
echo

read -p "Current pkgver is: ${cPkgVer}! Update? (y/n): " YN
case $YN  in
	y | Y )
		read -p "Oki. What should new pkgver be?: " newVersion
		sed -i  "0,/pkgver/s/.*pkgver.*/pkgver=${newVersion}/" PKGBUILD
		cPkgVer=$(sed -n 's/\(^pkgver=\)//p' PKGBUILD	)
		echo "Oki, pkgver is now: ${cPkgVer}!"
		;;
	n | N )
		echo "Oki. Moving on!"
		echo
		;;
esac

read -p "Current pkgrel is: ${cPkgRel}! Update? Press enter to increment by one, y to specify new pkgrel, or N to not change. : " YN
case $YN  in
	y | Y )
		read -p "Oki. What should new pkgrel be?: " newRel
		sed -i  "0,/pkgrel/s/.*pkgrel.*/pkgrel=${newRel}/" PKGBUILD
		cPkgRel=$(sed -n 's/\(^pkgrel=\)//p' PKGBUILD	)
		echo "Oki, pkgrel is now: ${cPkgRel}!"
		;;
	n | N )
		echo "Oki. pkgrel will remain ${cPkgRel}!"
		echo
		;;
	* )
		echo "Oki. Incrementing by one then!"
		echo
		((cPkgRel+=1))
		newRel=$cPkgRel
		sed -i  "0,/pkgrel/s/.*pkgrel.*/pkgrel=${newRel}/" PKGBUILD
		cPkgRel=$(sed -n 's/\(^pkgrel=\)//p' PKGBUILD	)
		echo "Oki, pkgrel is now: ${cPkgRel}"
		;;
esac

read -p "Need to update anything else in PKGBUILD? (y/n): " YN
echo
case $YN  in
	y | Y )
		nano -w PKGBUILD
		cPkgVer=$(sed -n 's/\(^pkgver=\)//p' PKGBUILD	)
		cPkgRel=$(sed -n 's/\(^pkgrel=\)//p' PKGBUILD	)
		cPkgName=$(sed -n 's/\(^pkgname=\)//p' PKGBUILD | sed 's/\([^"]*\)./\1/gi')
		cPkgArch=$(sed -n 's/\(^arch=\)//p' PKGBUILD | sed 's/\([^"]*\)./\1/gi')
		package="${cPkgName}-${cPkgVer}-${cPkgRel}-${cPkgArch}.pkg.tar.zst"
		;;
	n | N )
		echo "Oki. Moving on!"
		;;
esac

if [[ $destRepo = "$devRepo" ]]; then
	sudo sed -i  "0,/buildVersion/s/.*buildVersion.*/buildVersion=${cPkgVer}-${cPkgRel}/" /etc/dab/dev/.functions
else
	sudo sed -i  "0,/buildVersion/s/.*buildVersion.*/buildVersion=${cPkgVer}-${cPkgRel}/" /etc/abs/misc/.functions
fi

echo "Pushing latest ${cPkgName} changes to ${cPkgName}'s git repo before creating a new ${cPkgName} pkg tar!"
git add -A
git commit -m "${cPkgName}-${cPkgVer}-${cPkgRel}"
git push
echo "Oki, time to build!"
makepkg --sign
rm -rf pkg/
echo
echo "Oki now we move new ${cPkgName} pkg to ${destRepo} and begin push!"
mv *.pkg.tar.zst *.pkg.tar.zst.sig ../$destRepo/x86_64/
cd ../$destRepo/x86_64/
repo-add -v -s -R $destRepo.db.tar.gz *.pkg.tar.zst
cd ..
git add -A
git commit -m "${cPkgName}-${cPkgVer}-${cPkgRel}"
git push
echo
echo "${txUnderline}Done, don't forget repo update takes a few minutes to be available through pacman${txReset}!"
