#!/bin/bash

cd

user=$(whoami)

mkdir Arch-Vanilla
mkdir Arch-Vanilla/ISO
mkdir Arch-Vanilla/Build

cp -r /usr/share/archiso/configs/releng/ Arch-Vanilla/

cd Arch-Vanilla/

profile=releng
outDir=ISO/
buildDir=Build/

valenRepoAdder

echo "We are all setup to build a Vanilla Arch Monthly ISO. Lets Begin!"
echo "ISO will be found in a folder within this directory labeled ISO!"
echo "Build folder will be labeled build!"
echo "This will take a bit so perhaps make some coffee!"

sudo mkarchiso -v -w $buildDir -o $outDir $profile
sudo chown -R $user $buildDir
sudo chown -R $user $outDir
