#!/bin/bash
# https://keyaedisa.github.io/

source /etc/abs/misc/.bashFormatting
source /etc/abs/misc/.functions
source /etc/abs/.options

if [[ $1 == "-c" || $1 == "--custom" ]]; then
	custom
elif [[ $1 == "-h" || $1 == "--help" ]]; then
	helpOpt $1
elif [[ $1 == "-V" || $1 == "--version" ]]; then
	currentVersion
elif  [[ $1 == "-v" || $1 == "--releng" ]]; then
	vanilla
elif  [[ $1 == "-vb" || $1 == "--baseline" ]]; then
	vanillaBaseline
elif [[ $1 == "-x" || $1 == "--xero" || $1 == "xero" || $1 == "Xero" ]]; then
	xero
elif  [[ $1 == "-xg" || $1 == "--xerog" || $1 == "xerog" || $1 == "XeroG"  ]]; then
	xerog
elif [[ -n $1 ]]; then # If stdin is a not empty string not matching any  of the previous conditions then:
	echo "Sorry, abs does not recognize this option. Run ${fgCyan}abs -h${txReset} or ${fgCyan}abs --help (for more detailed version)${txReset} to display help message."
else
	listOptions
	read -p "What option would you like to select? " answer
	finished='0'
	case $answer in
		-c | --custom )
			finished='1'
			custom
			;;
		-h | --help )
			helpOpt $answer
			;;
		-V | --version )
			currentVersion
			;;
		-v | --releng )
			finished='1'
			vanilla
			;;
		-vb | --baseline )
			finished='1'
			vanillaBaseline
			;;
		-x | --xero | xero | Xero )
			finished='1'
			xero
			;;
		-xg | --xerog | xerog | XeroG )
			finished='1'
			xerog
			;;
		* )
			echo "Not a valid abs option."
			echo
			listOptions
			read -p " Choose from an option ${fgCyan}above${txReset} or enter ${fgCyan}abs -h/--help${txReset} for help.  " answer
			;;
	esac
fi
